import type { SearchItem } from './types';

export const mockSearchItems: SearchItem[] = [
  {
    id: 'task-change-hvac-filter',
    kind: 'task',
    label: 'Change HVAC filter',
    description: 'Maintenance · Anderson Household',
    keywords: ['furnace', 'air filter', 'heating', 'cooling'],
    meta: 'Today',
    to: '/tasks',
  },
  {
    id: 'task-check-crawlspace',
    kind: 'task',
    label: 'Check crawlspace after rain',
    description: 'Maintenance · Anderson Household',
    keywords: ['basement', 'water', 'storm', 'inspection'],
    meta: 'Tomorrow',
    to: '/tasks',
  },
  {
    id: 'task-buy-potting-soil',
    kind: 'task',
    label: 'Buy potting soil',
    description: 'Errands · Anderson Household',
    keywords: ['garden', 'plants', 'shopping'],
    meta: 'Due soon',
    to: '/tasks',
  },
  {
    id: 'note-hvac-service-history',
    kind: 'note',
    label: 'HVAC service history',
    description: 'Filter size, contractor details, and previous service',
    keywords: ['furnace', 'contractor', 'tune-up', 'maintenance record'],
    meta: 'Updated Aug 12',
    to: '/notes',
  },
  {
    id: 'note-emergency-contacts',
    kind: 'note',
    label: 'Emergency household contacts',
    description: 'Plumber, electrician, insurance, and utility numbers',
    keywords: ['phone', 'contractor', 'repair', 'utilities'],
    meta: 'Updated Aug 2',
    to: '/notes',
  },
  {
    id: 'page-today',
    kind: 'page',
    label: 'Today',
    description: 'See what needs attention today',
    keywords: ['dashboard', 'home', 'due now'],
    meta: 'Page',
    to: '/today',
  },
  {
    id: 'page-tasks',
    kind: 'page',
    label: 'Tasks',
    description: 'View and organize household work',
    keywords: ['chores', 'maintenance', 'errands', 'todo'],
    meta: 'Page',
    to: '/tasks',
  },
  {
    id: 'page-calendar',
    kind: 'page',
    label: 'Calendar',
    description: 'View upcoming household work by date',
    keywords: ['schedule', 'dates', 'upcoming'],
    meta: 'Page',
    to: '/calendar',
  },
  {
    id: 'page-household',
    kind: 'page',
    label: 'Household',
    description: 'Manage members and household settings',
    keywords: ['family', 'people', 'members', 'invite'],
    meta: 'Page',
    to: '/household',
  },
  {
    id: 'page-notes',
    kind: 'page',
    label: 'Notes',
    description: 'Browse shared household information',
    keywords: ['documents', 'reference', 'information'],
    meta: 'Page',
    to: '/notes',
  },
];