/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as preAuthWhyRouteImport } from './routes/(pre-auth)/why'
import { Route as preAuthResourcesRouteImport } from './routes/(pre-auth)/resources'
import { Route as preAuthPricingRouteImport } from './routes/(pre-auth)/pricing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const preAuthWhyRoute = preAuthWhyRouteImport.update({
  id: '/(pre-auth)/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)
const preAuthResourcesRoute = preAuthResourcesRouteImport.update({
  id: '/(pre-auth)/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const preAuthPricingRoute = preAuthPricingRouteImport.update({
  id: '/(pre-auth)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pricing': typeof preAuthPricingRoute
  '/resources': typeof preAuthResourcesRoute
  '/why': typeof preAuthWhyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof preAuthPricingRoute
  '/resources': typeof preAuthResourcesRoute
  '/why': typeof preAuthWhyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(pre-auth)/pricing': typeof preAuthPricingRoute
  '/(pre-auth)/resources': typeof preAuthResourcesRoute
  '/(pre-auth)/why': typeof preAuthWhyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pricing' | '/resources' | '/why'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pricing' | '/resources' | '/why'
  id:
    | '__root__'
    | '/'
    | '/(pre-auth)/pricing'
    | '/(pre-auth)/resources'
    | '/(pre-auth)/why'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  preAuthPricingRoute: typeof preAuthPricingRoute
  preAuthResourcesRoute: typeof preAuthResourcesRoute
  preAuthWhyRoute: typeof preAuthWhyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pre-auth)/why': {
      id: '/(pre-auth)/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof preAuthWhyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pre-auth)/resources': {
      id: '/(pre-auth)/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof preAuthResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pre-auth)/pricing': {
      id: '/(pre-auth)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof preAuthPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  preAuthPricingRoute: preAuthPricingRoute,
  preAuthResourcesRoute: preAuthResourcesRoute,
  preAuthWhyRoute: preAuthWhyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
